// ============================================================================
// 馬マスター（自動生成）/ Horse roster — generated by scripts/sync-horses.mjs
// 画像ファイル名（images/horses/）から馬名・保護順を抽出し、Supabase Storage の
// 公開URLを photo に設定しています。手動で編集せず、画像を追加/差し替えたら
//   node --env-file=.env.local scripts/sync-horses.mjs
// を再実行してください。管理画面(/admin)からの個別編集はDB側に反映されます。
// ============================================================================

export type RosterEntry = {
  slug: string;
  name: string;
  sex?: "牡" | "牝" | "騙";
  age?: string;
  status: "protected" | "graduated" | "owner";
  statusLabel: string;
  order?: number;
  personality?: string;
  story?: string;
  before?: string;
  photo: string;
  note?: string;
  goal: number;
  raised: number;
  supporters: number;
};

export const ROSTER: RosterEntry[] = [
  {"slug":"horse-00","name":"マッシュ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":0,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-00.jpg","note":"繊細で再調教に時間が必要。月々の飼養費が大きく不足しています。","goal":200000,"raised":36000,"supporters":12},
  {"slug":"horse-01","name":"パヴォーネ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":1,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-01.jpg","note":"肥育場から保護されたばかり。健康管理と治療の支援を募集中です。","goal":180000,"raised":41000,"supporters":15},
  {"slug":"horse-02","name":"ハル","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":2,"personality":"穏やか・人なつっこい","story":"肥育場から救い出された一頭。見学会では子どもたちの人気者。リトレーニングを経て乗馬への道を歩んでいます。","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-02.jpg","note":"人なつっこい人気者ですが、継続支援が目標に届いていません。","goal":200000,"raised":58000,"supporters":22},
  {"slug":"horse-03","name":"エル","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":3,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-03.jpg","note":"若く伸びしろのある一頭。蹄の治療費の支援が必要です。","goal":180000,"raised":64000,"supporters":19},
  {"slug":"horse-04","name":"ケン","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":4,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-04.jpg","note":"リトレーニング中。あと一歩で月間目標に届きます。","goal":190000,"raised":78000,"supporters":28},
  {"slug":"horse-05","name":"ハオ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":5,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-05.jpg","note":"高齢でケア費用がかさむため、長期の支援者を探しています。","goal":210000,"raised":99000,"supporters":31},
  {"slug":"horse-06","name":"ノア","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":6,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-06.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-07","name":"ブライト","age":"不明","status":"owner","statusLabel":"オーナー決定馬","order":7,"personality":"すごく優しいお父さんのような存在","story":"おとなしい性格で、だれからも可愛がられている存在。オーナーが決まり長野県へ。","before":"肥育場の厩舎ではドロドロになりながらも一生懸命生きている感じが伝わってきた。","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-07.jpg","note":"指導馬として活躍中。応援の輪が広がっています。","goal":180000,"raised":138000,"supporters":69},
  {"slug":"horse-08","name":"ピノ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":8,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-08.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-09","name":"つむぎ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":9,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-09.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-10","name":"アイ","age":"不明","status":"owner","statusLabel":"オーナー決定馬","order":10,"personality":"元気な妹！ニコがお兄ちゃん的存在","story":"アイとニコ同時に譲渡決定。熊本の個人オーナーさんのもと元気に過ごしています。","before":"ニコ号がお兄ちゃん、アイ号が妹。ニコとアイはとても仲良しでした。","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-10.jpg","note":"オーナー決定後も多くのサポーターに見守られています。","goal":160000,"raised":132000,"supporters":74},
  {"slug":"horse-11","name":"ニコ","age":"不明","status":"owner","statusLabel":"オーナー決定馬","order":11,"personality":"まさにお兄ちゃん的存在。優しい～","story":"アイとニコ同時に譲渡決定。熊本の個人オーナーさんのもと元気に過ごしています。","before":"肥育場でのお部屋にニコとアイが一緒に支え合ってる感じ。二人とも同時に受入れ。","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-11.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-12","name":"カリン","age":"不明","status":"owner","statusLabel":"オーナー決定馬","order":12,"personality":"顔のつくりがとても美しい美人さん","story":"この子の素晴らしさを理解して頂いたオーナー様にすぐ面会して頂き決定。九州へ。","before":"顔がとてもきれいな整ったつくりで特徴的でした。すぐに目に留まり引取りを決定。","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-12.jpg","note":"クラウドファンディング発の人気馬。応援が集まっています。","goal":190000,"raised":165000,"supporters":88},
  {"slug":"horse-13","name":"メメ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":13,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-13.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-14","name":"シャイン","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":14,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-14.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-15","name":"ヒメ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":15,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-15.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-16","name":"テラ","age":"不明","status":"owner","statusLabel":"オーナー決定馬","order":16,"personality":"とても穏やかで癒し系の人気者","story":"常に冷静で安心感。約1年のオーナー預託を経て北海道のプライベート乗馬施設へ。","before":"緊張下にある肥育場の厩舎でも、優しく人懐っこい性格でお利口さんな感じがした。","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-16.jpg","note":"乗用馬デビューを果たし、たくさんの応援が集まりました。","goal":170000,"raised":156000,"supporters":96},
  {"slug":"horse-17","name":"ユメ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":17,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-17.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-18","name":"アユミ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":18,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-18.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-19","name":"イヴ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":19,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-19.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-20","name":"アキラ","age":"不明","status":"owner","statusLabel":"オーナー決定馬","order":20,"personality":"まだ若い元気な男の子","story":"肥育場から引き取り後、運命的な出会いを感じて頂いた個人オーナー様に譲渡決定。","before":"肥育場の中でもまだ若さと幼さが垣間見える。せっかく生まれた命を大切にしたい。","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-20.jpg","note":"馬術競技馬を目指して調教中。目標達成まであと一歩です。","goal":200000,"raised":192000,"supporters":128},
  {"slug":"horse-21","name":"サニー","age":"不明","status":"owner","statusLabel":"オーナー決定馬","order":21,"personality":"顔は鋭いけどすごく優しいギャップ","story":"とても大人しく扱いも騎乗もとても安心できる子で個人のオーナー様への譲渡決定。","before":"お顔はキリッと強そうなイメージ。しかし、本当に人にも馬にも優しい子の予感が。","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-21.jpg","note":"ほぼ満額を達成。多くのサポーターに支えられています。","goal":180000,"raised":178000,"supporters":142},
  {"slug":"horse-22","name":"ココロ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":22,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-22.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-23","name":"アンジュ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":23,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-23.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-24","name":"ヒナタ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":24,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-24.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-25","name":"ラファ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":25,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-25.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-26","name":"トワ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":26,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-26.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-27","name":"チャコ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":27,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-27.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-28","name":"ヒカル","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":28,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-28.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-30","name":"アイリス","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":30,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-30.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-31","name":"ミラクル","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":31,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-31.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-32","name":"ククナ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":32,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-32.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-33","name":"マリア","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":33,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-33.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-34","name":"フォルトゥーナ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":34,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-34.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-36","name":"イメル","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":36,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-36.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-37","name":"カエデ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":37,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-37.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-38","name":"ホープ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":38,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-38.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-39","name":"ダイチ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":39,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-39.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-40","name":"アルコンシエル","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":40,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-40.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-41","name":"ルル","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":41,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-41.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-42","name":"ミラーダ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":42,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-42.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-43","name":"エトワール","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":43,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-43.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-44","name":"ラテ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":44,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-44.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-45","name":"イチョウ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":45,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-45.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-46","name":"ピュア","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":46,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-46.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-47","name":"さくら","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":47,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-47.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-48","name":"ミルキー","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":48,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-48.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-49","name":"ピース","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":49,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-49.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-50","name":"アース","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":50,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-50.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-51","name":"ミント","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":51,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-51.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"horse-52","name":"サチ","age":"不明","status":"protected","statusLabel":"現在の保護馬","order":52,"photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/horse-52.jpg","goal":0,"raised":0,"supporters":0},
  {"slug":"sakura-ace","name":"サクラエース","age":"不明","status":"graduated","statusLabel":"卒業馬","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/sakura-ace.webp","goal":0,"raised":0,"supporters":0},
  {"slug":"hayate-boy","name":"ハヤテボーイ","age":"不明","status":"graduated","statusLabel":"卒業馬","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/hayate-boy.webp","goal":0,"raised":0,"supporters":0},
  {"slug":"midori-no-kaze","name":"ミドリノカゼ","age":"不明","status":"graduated","statusLabel":"卒業馬","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/midori-no-kaze.webp","goal":0,"raised":0,"supporters":0},
  {"slug":"pony-rescue","name":"救済ポニー","age":"不明","status":"protected","statusLabel":"現在の保護馬","photo":"https://kwytnjcghauwbqzgwnxo.supabase.co/storage/v1/object/public/horse-images/pony-rescue.webp","note":"目を負傷したポニーの救済支援。番外編として保護しました。","goal":0,"raised":0,"supporters":0},
];
